export use "bat-completion.nu" *
export use "cargo-completion.nu" *
export use "eza-completion.nu" *
export use "git-completion.nu" *
export use "just-completion.nu" *
export use "pnpm-completion.nu" *
export use "rg-completion.nu" *
export use "rustup-completion.nu" *
export use "zellij-completion.nu" *
