"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false
format = """
$username\
$hostname\
$directory\
$time$cmd_duration\
$git_branch$git_status\
$status
$character
"""
right_format = "$all"

[character]
error_symbol = '[✗](bold red)'
success_symbol = '[➜](bold green)'

[cmd_duration]
format = '[$duration]($style) '
min_time = 500
show_milliseconds = true

[aws]
symbol = "  "

[battery]
disabled = true

[buf]
symbol = " "

[c]
symbol = " "

[conda]
symbol = " "

[dart]
symbol = " "

[directory]
read_only = " 󰌾"
truncate_to_repo = false
truncation_length = 5
truncation_symbol = '…/'

[docker_context]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[fossil_branch]
symbol = " "

[git_branch]
symbol = " "

[git_status]
ahead = '⇡${count}'
behind = '⇣${count}'
modified = ' ${count}'
stashed = ' ${count} '

[golang]
symbol = " "

[guix_shell]
symbol = " "

[haskell]
symbol = " "

[haxe]
symbol = " "

[hg_branch]
symbol = " "

[hostname]
format = '[$ssh_symbol$hostname]($style) '
ssh_only = false
ssh_symbol = " "
style = 'bold green'

[java]
symbol = " "

[julia]
symbol = " "

[lua]
symbol = " "

[memory_usage]
symbol = "󰍛 "

[meson]
symbol = "󰔷 "

[nim]
symbol = "󰆥 "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "

[os.symbols]
Alpaquita = " "
Alpine = " "
Amazon = " "
Android = " "
Arch = " "
Artix = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
OpenBSD = "󰈺 "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
RedHatEnterprise = " "
Redhat = " "
Redox = "󰀘 "
SUSE = " "
Solus = "󰠳 "
Ubuntu = " "
Unknown = " "
Windows = "󰍲 "
openSUSE = " "

[package]
symbol = "󰏗 "

[pijul_channel]
symbol = " "

[python]
symbol = " "

[rlang]
symbol = "󰟔 "

[ruby]
symbol = " "

[rust]
symbol = " "

[scala]
symbol = " "

[status]
disabled = false
format = '[$symbol $status]($style) '

[time]
disabled = false
format = '[[  $time ](fg:#a0a9cb)]($style)'
style = "bg:#1d2230"
time_format = "%R"

[username]
format = '[$user]($style)@'
show_always = true
style_user = "bold green"
